DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

autoweb/urls.py
from django.conf.urls import *
from django.contrib import admin
from django.contrib.auth.views import login
from DjangoUeditor import urls
from django.conf import settings
from service.views import *
from api.views import *
from chart.views import *
from timetask import views

urlpatterns = [
    url(r'^admin/chart/chartconfig/', index, name='index'),
    url(r'^timetask/start_task/(?P<task_id>[0-9]+$)', views.start_task, name='start_task_page'),
    url(r'^admin/timetask/plantastconfig/$', views.time_task_page, name='time_task_page'),
    url(r'^timetask/stop_task/(?P<task_id>[0-9]+$)', views.stop_task, name='stop_task_page'),
    url(r'^timetask/del_task/(?P<task_id>[0-9]+$)', views.del_task, name='del_task_page'),
    url(r'^admin/', admin.site.urls),
    url(r'^ueditor/', include(urls)),
    url(r'^index/',index,name='index'),
    url(r'^test/',test_page,name='test'),
    url(r'^check',check_page,name='check'),
    url(r'^add/', add, name='add'),
    # url(r'^column/(?P<column_slug>[^/]+)/$', column_detail, name='column'),
    # url(r'^services/(?P<pk>\d+)/(?P<article_slug>[^/]+)/$', article_detail, name='article'),
    url(r'^service/get_class/(?P<project_id>[0-9]+)$',get_class),
    url(r'^timetask/get_plan_info/(?P<plan_id>[0-9]+)$',views.get_plan_info),
    url(r'^api/get_class/(?P<project_id>[0-9]+)$',get_api_class),
]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

api/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
# from django.utils.html import format_html

# Create your models here.


@python_2_unicode_compatible
class ApiTest(models.Model):
    project_name = models.ForeignKey('ProjectConfig',verbose_name='项目',null=False)
    class_name = models.ForeignKey('VersionConfig',verbose_name='版本',null=False)
    name = models.CharField('接口名称',max_length=256,null=False)
    is_run = models.BooleanField('状态',default=False)
    pre_data_file = models.FileField('数据文件', upload_to='uploads/script/',null=True,blank=True)
    script_path = models.FileField('用例文件',upload_to='uploads/script/',null=True,blank=True)
    schedule = models.CharField('进度',max_length=256,null=True,blank=True)
    result = models.FileField('执行结果', upload_to='uploads/script/')
    creater = models.CharField('创建人',max_length=256,null=True,blank=True)

    def __str__(self):
        return self.name

    # def colored_name(self):
    #     if self.schedule == '100%':
    #         color_code ='green'
    #     else:color_code = 'red'
    #     # self.color_code = 'green'
    #     return format_html(
    #         '<span style="color: #{};">{} {}</span>',
    #         color_code,
    #         self.name,
    #     )
    class Meta:
        verbose_name = 'API用例管理'
        verbose_name_plural = 'API用例管理'
        ordering = ['name']


@python_2_unicode_compatible
class ProjectConfig(models.Model):
    name = models.CharField('接口项目',max_length=256,null=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '项目配置'
        verbose_name_plural = '项目配置'


@python_2_unicode_compatible
class VersionConfig(models.Model):
    name = models.CharField('版本',max_length=256,null=False)
    project = models.ForeignKey('ProjectConfig',verbose_name='所属项目',null=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '版本配置'
        verbose_name_plural = '版本配置'

chart/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from service.models import ProjectConfig

# Create your models here.
@python_2_unicode_compatible
class ChartConfig(models.Model):
    name = models.CharField(max_length=256, null=False)
    class_name = models.CharField(max_length=256, null=False)
    function_name = models.CharField(max_length=256, null=False)
    chart_type = models.CharField(max_length=256, null=False)
    success = models.IntegerField()
    failed = models.IntegerField()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '结果图表'
        verbose_name_plural = '结果图表'

timetask/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from service.models import ProjectConfig
from django.core.urlresolvers import reverse

# Create your models here.
@python_2_unicode_compatible
class TimeTaskConfig(models.Model):
    name = models.CharField('任务名称',max_length=256)
    plan_info = models.ManyToManyField(ProjectConfig, verbose_name=u'自动化项目')
    plan_type = models.ForeignKey('PlanTypeConfig',max_length=256,verbose_name='任务类型')
    plan_time = models.ForeignKey('PlanTimeConfig', max_length=256,verbose_name='具体执行日期')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '计划定时任务'
        verbose_name_plural = '计划定时任务'

@python_2_unicode_compatible
class TotalProjects(models.Model):
    project_type = models.CharField('项目类型',max_length=256)
    project_name = models.CharField('项目名称',max_length=256)

    def __str__(self):
        return self.project_name

@python_2_unicode_compatible
class PlanTastConfig(models.Model):
    name = models.CharField('任务名称(不支持中文)',max_length=256)
    plan_info = models.ManyToManyField(TotalProjects, verbose_name=u'自动化项目')
    plan_type = models.ForeignKey('PlanTypeConfig',max_length=256,verbose_name='任务类型')
    plan_time = models.ForeignKey('PlanTimeConfig', max_length=256,verbose_name='具体执行日期(h)')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '计划任务'
        verbose_name_plural = '计划任务'


@python_2_unicode_compatible
class PlanTypeConfig(models.Model):
    name = models.CharField('任务类型',max_length=256)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '计划类型配置'
        verbose_name_plural = '计划类型配置'





@python_2_unicode_compatible
class PlanTimeConfig(models.Model):
    plan_type = models.ForeignKey('PlanTypeConfig',max_length=256,verbose_name='任务类型')
    name = models.CharField('具体执行日期',max_length=256)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '计划执行配置'
        verbose_name_plural = '计划执行配置'

chart/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from models import ChartConfig
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from AutoTestService.run_main.run_test import get_db_info
from autoweb.settings import *
from django.contrib.auth.views import login_required
# Create your views here.
@staff_member_required
@login_required
def index(request):
    # home_display_columns = Column.objects.filter(home_display=True)
    # nav_display_columns = Column.objects.filter(nav_display=True)
    chart_info = []
    success_list = []
    failed_list = []
    success_dic = {}
    failed_dic = {}
    service_result_file = api_result_file = ""
    chart_items = ChartConfig.objects.all()
    i = j = 0
    for item in chart_items:
        print item
        chart_type = item.chart_type.encode("utf-8")
        project_name = item.name.encode("utf-8")
        if chart_type == "service" and i == 0:
            case_info = get_db_info("service",item.function_name.encode("utf-8"))
            print case_info
            if len(case_info)>0:
                service_result_file = MEDIA_URL + case_info[0][6]
                i += 1
        if chart_type == "api" and j == 0:
            case_info = get_db_info("api",item.function_name.encode("utf-8"))
            api_result_file = MEDIA_URL + case_info[0][6]
            j += 1
        if project_name not in chart_info:
            chart_info.append(project_name)
        if success_dic.has_key(project_name):
            success_number = success_dic.get(project_name)
            success_number += item.success
            success_dic[project_name] = success_number
        else:success_dic[project_name] = item.success
        if failed_dic.has_key(project_name):
            failed_number = failed_dic.get(project_name)
            failed_number += item.failed
            failed_dic[project_name] = failed_number
        else:failed_dic[project_name] = item.failed
    for chart_item in chart_info:
        success_list.append(success_dic.get(chart_item))
        failed_list.append(failed_dic.get(chart_item))
    options = {
        'xAxis': chart_info,
        'series_data': {
            'success': success_list,
            'failed': failed_list,
        }
    }
    print service_result_file,api_result_file
    # columns = Column.objects.all()
    return render(request, 'chart.html', {
        'option': options,
        'service_result_file':service_result_file,
        'api_result_file':api_result_file,
    })
    # return HttpResponse(u'欢迎来到测试首页')

timetask/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from AutoTestService.run_main import run_test
from django.shortcuts import render
import time,json
from .models import PlanTimeConfig,PlanTastConfig
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def time_task_page(request):
    plan_info = PlanTastConfig.objects.all()
    result = []
    for item in plan_info:
        act_task_info = run_test.get_sqlite_info(item.name)
        status = run_test.get_task_status(str(item.name))
        result.append({'id': item.id,
                       'name': item.name,
                       'status':status,
                       'task_type':str(item.plan_type),
                       'plan_time':item.plan_time,
                       'run': 1 if len(act_task_info) > 0 else 0,
                       'next_time': time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(act_task_info[0][1])) if len(act_task_info)>0 else ''})
    # for i in range(len(aa)):
    #     print aa[i][0],aa[i][1],aa[i][2]
    #     result.append({'id': aa[i][0], 'next_time': time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(aa[i][1]))})
        # result.append({'id':aa[i][0],'next_time':time.strftime("%Y-%m-%d %H:%M:%S",time.localtime(aa[i][1]))})
    # print aa
    return render(request,"admin/timetask/timetaskconfig/change_list.html",{'task':result})


def change_form(request):
    return render(request,'admin/timetask/timetaskconfig/change_list.html')


@login_required
def stop_task(request,task_id):
    plan_info = PlanTastConfig.objects.filter(id=task_id)
    task_name = plan_info[0].name
    # project_name =plan_info[0].project_name
    run_test.stop_task(task_name)
    # Data.stop_plan(task_name)
    # aa = plan.stop_plan()
    # return render(request, "timetask.html")
    return HttpResponseRedirect("/admin/timetask/plantastconfig/")
    # return render(request,"timetask.html")


@login_required
def del_task(request,task_id):
    plan_info = PlanTastConfig.objects.filter(id=task_id)
    task_name = plan_info[0].name
    # project_name = plan_info[0].project_name
    run_test.del_task(int(task_id),task_name)
    # Data.stop_plan(task_name)
    # Data.del_db_info("","","where id = %d"% int(task_id))
    # aa = plan.stop_plan()
    # return render(request, "timetask.html")
    return HttpResponseRedirect("/admin/timetask/plantastconfig/")
    # return render(request,"timetask.html")


@login_required
def start_task(request,task_id):
    # task_id = task_info.split('_')[1]
    plan_info = PlanTastConfig.objects.filter(id=task_id)
    task_name = plan_info[0].name
    # project_name = plan_info[0].project_name
    plan_type = plan_info[0].plan_type
    plan_time =plan_info[0].plan_time
    # print type(plan_type)
    # print type(u'豆豆豆')
    # print type(str(plan_type))
    run_info={'run_type':str(plan_type),'run_time':str(plan_time)}
    print run_info
    run_test.start_task(task_name,run_info,True)
    # Data.write_run_task(project_name,task_name,is_run=True)
    # Data.PlanTimeTask(task_name)
    # Data.start_plan_task(job,task_name)
    return HttpResponseRedirect("/admin/timetask/plantastconfig/")


@login_required
def get_plan_info(request, plan_id):
    plan_info = PlanTimeConfig.objects.filter(plan_type=plan_id)
    # print plan_info
    result = []
    for i in plan_info:
        result.append({'id':i.id,'name':i.name})
    return HttpResponse(json.dumps(result),content_type="application/json")

templates/base_site.html
{% extends "admin/base_site.html" %}

{% block content %}
{#    {% block object-tools %}#}
{#    <a href="/admin/timetask/timetaskconfig/add/" class="btn btn-success">#}
{#                    <i class="icon-plus-sign icon-white"></i>&nbsp;#}
{#                    增加 计划任务#}
{#                  </a>#}
{#{% endblock %}#}
<link rel="stylesheet" type="text/css" href="/media/css/sched.css">

<div class="results">
       <table width="100%" border="0" cellpadding="4" cellspacing="1" bgcolor="#cccccc" class="tabtop13" align="center" >
           <tr>
               <th width="10%"  class="btbg font-center titfont" >任务id</th>
               <th width="10%" class="btbg font-center titfont" >下次执行时间</th>
               <th width="10%" class="btbg font-center titfont" >是否执行</th>
               <th width="10%" class="btbg font-center titfont" >操作</th>
           </tr>
           {% for foo in task %}
                    <td width="10%" class="font-center">{{ foo.id }}</td>
               <td width="10%" class="font-center">{{ foo.next_time }}</td>
               <td width="10%" class="font-center">
                   <img src="/media/img/icon-yes.svg">
               </td>
               <td style="text-align: center;">
                            <div class="btn-group">
                                <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                                    任务操作
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" style="width: 100px;">
{#                                    <li><button type="submit" class="btn btn-success"> 开始任务 </button></li>#}
                                     <li><button type="submit" id="id_end" class="btn btn-danger stop-status"> 停止任务 </button></li>
                                    <li><a href="/CardPlan/PromoCardPlanDetail?id=902988">删除任务</a></li>
                                                                        <!--<li class="divider"></li>
                                <li><a href="/CardPlan/ForbidPromoCardPlan?id=">禁用</a></li>-->
                                                                    </ul>
                            </div>
                        </td>
           </tr>
           {% endfor %}


{#           <tr>#}
{#               <td width="10%" class="font-center">ssssss</td>#}
{#               <td width="10%" class="font-center">2017-10-11</td>#}
{#               <td width="10%" class="font-center">#}
{#                   <img src="/media/img/icon-yes.svg">#}
{#               </td>#}
{#               <td style="text-align: center;">#}
{#                            <div class="btn-group">#}
{#                                <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">#}
{#                                    任务操作#}
{#                                    <span class="caret"></span>#}
{#                                </a>#}
{#                                <ul class="dropdown-menu" style="width: 100px;">#}
{#                                    <li><button type="submit" class="btn btn-success"> 开始任务 </button></li>#}
{#                                     <li><button type="submit" id="id_end" class="btn btn-danger stop-status"> 停止任务 </button></li>#}
{#                                    <li><a href="/CardPlan/PromoCardPlanDetail?id=902988">删除任务</a></li>#}
{#                                                                        <!--<li class="divider"></li>#}
{#                                <li><a href="/CardPlan/ForbidPromoCardPlan?id=">禁用</a></li>-->#}
{#                                                                    </ul>#}
{#                            </div>#}
{#                        </td>#}
{#           </tr>#}
{#           <tr>#}
{#               <td width="10%" id="id_ssssss" class="font-center">ssssss</td>#}
{#               <td width="10%" class="font-center">2017-10-11</td>#}
{#               <td width="10%" class="font-center">#}
{#                   <img src="/media/img/icon-no.svg">#}
{#               </td>#}
{#                <td style="text-align: center;">#}
{#                            <div class="btn-group">#}
{#                                <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">#}
{#                                    任务操作#}
{#                                    <span class="caret"></span>#}
{#                                </a>#}
{#                                <ul class="dropdown-menu" style="width: 100px;">#}
{#                                    <li><button type="submit" class="btn btn-success"> 开始任务 </button></li>#}
{#                                     <li><button type="submit" class="btn btn-success"> 开始任务 </button></li>#}
{#                                    <li><a href="/CardPlan/PromoCardPlanDetail?id=902988">删除任务</a></li>#}
{#                                                                        <!--<li class="divider"></li>#}
{#                                <li><a href="/CardPlan/ForbidPromoCardPlan?id=">禁用</a></li>-->#}
{#                                                                    </ul>#}
{#                            </div>#}
{#                        </td>#}
{#           </tr>#}
       </table>
    </div>
<script type="text/javascript" src="/media/js/django/jquery.init.js"></script>
<script>
    django.jQuery(function() {
        var select = django.jQuery("#id_end");
        var datas = django.jQuery("#id_ssssss");
        select.click(function(){
            console.log(datas[0].innerText)
            var url = "/timetask/end_task/"+datas[0].innerText;//能够正确的访问到view的url
{#            console.log(url);#}
            django.jQuery.get(
                url,
                function(data){
                    console.log(222)
{#                    var target = django.jQuery("#id_class_name");#}
{#                    target.empty();//先要清空一下#}
{#                    data.forEach(function(e){#}
{#                        // 将从view得到的id和城市名称赋值给city的select#}
{#                        console.log(e);#}
{#                        target.append("<option value='"+e.id+"'>"+e.name+"</option>");#}
{#                        target.eq(0).attr('selected', 'true');#}
{#                        console.log(target);#}
{#                    });#}
            })
        });

    });
{#    $(function(){#}
{#        $('.stop-status').bind('click', function (e) {#}
{#            e.preventDefault();#}
{#            var url = "timetask/endtask";#}
{#            console.log(url)#}
{#            $.get({#}
{#                url: url#}
{#            }).success(function () {#}
{#                console.log(111)#}
{#            }).error(function () {#}
{#                console.log(222)#}
{#            });#}
{#        });#}
{##}
{#    });#}
</script>
{% endblock %}

templates/chart.html
{% extends "admin/base_site.html" %}
{% block content %}
<script src="/media/js/highcharts.js"></script>
<script src="/media/js/modules/exporting.js"></script>

<div id="chart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
    <br>
    {% if api_result_file != "" %}
        api接口测试：<a href={{ api_result_file }}>api接口测试的结果快速下载通道>></a><br>
    {% endif %}
    {% if service_result_file != "" %}
        service接口测试：<a href={{ service_result_file }}>service接口测试结果快速下载通道>></a><br>
    {% endif %}

		<script type="text/javascript">

Highcharts.chart('chart', {
    chart: {
        type: 'column',
    },
    title: {
        text: '自动化执行结果展示'
    },
    subtitle: {
        text: 'Source: 柱状图'
    },
    xAxis: {
        categories: {{ option.xAxis | safe }},
        crosshair: true
    },
    yAxis: {
        min: 0,
        title: {
            text: '用例数 (个)'
        }
    },
    tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
            '<td style="padding:0"><b>{point.y:1f} 个</b></td></tr>',
        footerFormat: '</table>',
        shared: true,
        useHTML: true
    },
    plotOptions: {
        column: {
            pointPadding: 0.2,
            borderWidth: 0,
            dataLabels:{
                enabled:true
            }
        }
    },
    series: [{
        name: 'Pass',
        data: {{ option.series_data.success | safe }},
        color: 'green'

    }, {
        name: 'Failed',
        data: {{ option.series_data.failed | safe }},
        color: 'red'

    }]
});
		</script>

{% endblock %}

templates/check.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>数据检查</title>
    <link rel="stylesheet" type="text/css" href="../media/css/main.css">
</head>
<body>
<form id="create" method="post">
    {% csrf_token %}
    操作的类型：{{ form.select_type }}
{#    <select id="option_type" name="select_type">#}
{#        <option value="check_format">检查格式</option>#}
{#        <option value="array_json">array转json</option>#}
{#        <option value="json_array">json转array</option>#}
{#    </select>#}
    <br>
{#请输入数据：<br><textarea name="check_data" id="id_check" style="width: 500px;height: 200px"></textarea>#}
请输入数据：<br>{{ form.check_data }}
<div id="container"></div>
    <input type="submit" id="ffff" value="点击进行处理" class="button" ><br>
{# <input id="org" type="button" value="添加" onclick="add_tr(this)"><br>#}
    数据结果:<br><textarea name="result" id="id_result" style="width: 500px;height: 200px">{{ test }}</textarea>

</form>


</body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>测试数据构造</title>
    <link rel="stylesheet" type="text/css" href="../media/css/main.css">
</head>
<body>
<form id="create" method="post">
   {% csrf_token %}
{#    {{ form.info.label }}:{{ form.info }}#}
{#    {{ form.db_name }}#}
{#    {{ form }}#}
    操作的类型：
    <select id="option_type" name="select_type" onchange="sele_change(this)">
        <option value="database">数据文件</option>
        <option value="redis">缓存</option>
        <option value="db_command">执行数据库命令</option>
        <option value="create_case">测试用例组装</option>
    </select>

{#{{ form.type }}#}
<div id="container"></div>
 <script type="text/javascript" src="../media/js/main.js"> </script>
<script>
     window.onload = function () {
         sele_change()
     }
</script>
    <script type="text/javascript">
        function sele_change (obj) {
        var select_type = select_change()
        if (select_type == "database")
        {
            document.getElementById("container").innerHTML =
                    '数据库实例：{{ form.info }} <br>数据库名称：{{ form.db_name }}<br>数据库表名：{{ form.table_name }}<br>'+
                    '插入 Sheet：{{ form.add_sheet }}<br>删除 Sheet：{{ form.del_sheet }}<br>文件的地址：'+
                    '<input type ="text" name ="file_path" style="width: 300px;"></input>'
{#             document.getElementById("container").innerHTML =#}
{#                    '数据库实例：{{ form.info }} <br>数据库名称：{{ form.db_name }}<br>数据库表名：{{ form.table_name }}<br>'+#}
{#                    '插入 Sheet：{{ form.add_sheet }}<br>删除 Sheet：{{ form.del_sheet }}<br>文件的地址：{{ form.file_path }}'#}
        }
        else if(select_type == "redis") {
{#            document.getElementById("container").clearAttributes()#}
              document.getElementById("container").innerHTML =
                   'redis &nbsp操作：    <select name="redis_option">'+
                    '<option value="get">get操作</option>'+
                    '<option value="set">set操作</option>'+
                    '<option value="del">del操作</option> <option value="hgetall">hgetall操作</option>   </select><br>'+
                    'redis &nbsp项目： {{ form.redis_info }} <br>' +
                    'redis &nbsp实例： {{ form.redis_name }} <br>'  +
                    'redis &nbsp键值： {{ form.redis_key }}（即：缓存key） <br>redis &nbsp数据： {{ form.redis_data }}<br>'
            }
        else if(select_type == "db_command") {
            document.getElementById("container").innerHTML =
                    '数据库实例：{{ form.info }} <br>数据库名称：{{ form.db_name }}<br>'+
                    '执行的语句：<input type ="text" name ="db_command_str" style="width: 300px;"></input>'
        }
        else
            document.getElementById("container").innerHTML =
                    '参数1：<input type ="text" name ="db_command_str" style="width: 300px;"></input>' +
                    '<input type="button" id="add" value="增加参数" onclick="add_item(this)" class="add" ><br>'
        }
        function add_item(obj) {
            var form = document.getElementById("container")
            v
        }

    </script>
{#    {{ form.type.label }}：{{ form.type }} <br>#}
{#    {{ form.info.label }}: {{ form.info }}<br>#}
{#    {{ form.db_name.label }}: {{ form.db_name }}<br>#}
{#    {{ form.table_name.label }}: {{ form.table_name }}<br>#}
{#    {{ form.add_sheet.label }}: {{ form.add_sheet }}<br>#}
{#    {{ form.del_sheet.label }}: {{ form.del_sheet }}<br>#}
{#    {{ form.file_path.label }}:<br> {{ form.file_path }}<br>#}
    <input type="submit" id="action" value="点击生成测试数据"  class="button" ><br>
{# <input id="org" type="button" value="添加" onclick="add_tr(this)"><br>#}
    数据结果(可直接复制到测试case中):<br><textarea name="result" id="id_result" style="width: 500px;height: 200px">{{ test }}</textarea>

</form>

<div>
</div>


</body>
</html>

templates/tttt.html
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="stylesheet" type="text/css" href="../media/css/sched.css">
</head>
<body>
<div class="results">
       <table width="100%" border="0" cellpadding="4" cellspacing="1" bgcolor="#cccccc" class="tabtop13" align="center" >
           <tr>
               <th width="10%"  class="btbg font-center titfont" >任务id</th>
               <th width="10%" class="btbg font-center titfont" >下次执行时间</th>
               <th width="10%" class="btbg font-center titfont" >是否执行</th>
               <th width="10%" class="btbg font-center titfont" >操作</th>
           </tr>
           <tr>
               <td width="10%" class="font-center">ssssss</td>
               <td width="10%" class="font-center">2017-10-11</td>
               <td width="10%" class="font-center">否</td>
               <td width="10%" class="font-center">
                   <div class="btn-group open">
                                <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                                    操作
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" style="width: 100px;">
                                    <li><a href="/CardPlan/PromoCardPlanDetail?id=902988">查看详情</a></li>
                                                                        <!--<li class="divider"></li>
                                <li><a href="/CardPlan/ForbidPromoCardPlan?id=">禁用</a></li>-->
                                                                    </ul>
                            </div>
               </td>
           </tr>
       </table>
    </div>
    </body>
</html>